name: Datalab

on:
  push:
    paths:
      - "datalab/*"
    branches:
      - main

jobs:
  datalab:
    name: Datalab
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          cd datalab
          ./dlc -e bits.c
          make btest
          ./btest
