name: Datalab

on:
  push:
    paths:
      - ".github/workflows/*"
      - "datalab/*"
      - "scripts/*"
    branches:
      - main

jobs:
  datalab:
    name: Datalab
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib

      - name: Test
        run: node scripts/test.js
